### ISSUE TITLE
about csv_log file

### ISSUE THREAD

**Issue by ZYHeunice** [chamathpali/FedSim#1]
In FedSim.py, missing csv_log file

**Comment by chamathpali** [comment]
@ZYHeunice can you clarify further? Log files will be created in the logs/ folder

**Comment by chamathpali** [comment]
@ZYHeunice thank you for noticing it. the utils folder had been missed in the repo. I have added it now. Also i have done a test run within this repo and looks working now. 
can you check it now with the latest commit?

**Comment by ZYHeunice** [comment]
yes, now it's working

**Comment by chamathpali** [comment]
Thanks for confirming 👍

**Comment by z1047310438** [comment]
@ZYHeunice Hello, may I ask which command you executed when running it? I failed to run it, or you can add your WeChat and we can discuss it.
